# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'Example', :exclusive => true do
pod "AESCrypt", :path => "../"
end

target 'ExampleSwift', :exclusive => true do
use_frameworks!
pod "AESCrypt", :path => "../"
end